---
title: " Exercises 3.1"
author: "Monica Alicea and Asha Silva"
date: "4/23/2021"
output: html_document
---
```{r}
# Exercise 3.1.1
# part one - replicate the figure 

# load the data
data <- read.table(
  "https://www.esrl.noaa.gov/gmd/webdata/ccgg/trends/co2/co2_mm_mlo.txt",
  col.names = c(
    "year", "month", "decidate", "moco2", "deseason", "nodays", "stdays",
    "uncertainty")
)

# create the plot 
par(tck = .02)
plot(data$decidate, data$moco2, type = 'l', col = 'red', lwd = 2,  xlab = "Year", ylab = "parts per million (ppm)", las = 1)
lines(data$decidate, data$deseason)
title(main = expression("Atmospheric CO"[2]* " at Mauna Loa Observatory"))
# top/bottom
axis(1, seq(1950,2030,10), tck = 0.04)
axis(1, seq(1950,2030,5), labels = FALSE)
axis(3, seq(1950,2030,10), labels = FALSE, tck = 0.04)
axis(3, seq(1950,2030,5), labels = FALSE)
# left/right
axis(2, seq(300,420,40), tck = 0.04, labels = FALSE)
axis(2, seq(300,420, 10), labels = FALSE)
axis(4, seq(300,420,40), labels = FALSE, 0.04)
axis(4, seq(300,420, 10), labels = FALSE)
text(1975, 410, "Scripps Institution of Oceanography")
text(1975, 400, "NOAA Global Monitoring Laboratory")


# part two - desasonalize the time series
summary(lm(data$moco2 ~ data$decidate))

# create the zero mean time series 
detrended <- data$moco2 - (predict(lm(data$moco2 ~ data$decidate)))
plot(detrended, type = 'l')

# Model the seasonality 
summary(lm(detrended ~ sin(data$decidate * 2 * pi) + cos(data$decidate * 2 * pi)))
```

```{r}
# Exercise 3.1.2
```
$$
X(t) = a(t) + 0.2 a(t-1) - 0.48 a(t-2)
$$

$$
\begin{align}
\rho_k &= \frac{-\theta_k + \sum_{j=1}^{q-k} \theta_j \theta_{j+k}}{1 + \sum_{j=1}^{q} \theta^2_j}, \, &k=1,2,..,q \\
&= 0,\, &k > q
\end{align}
$$

$$
\begin{align}
\rho_0 &= \frac{-\theta_0 + \sum_{j=1}^{2-0} \theta_j \theta_{j+0}}{1 + \sum_{j=1}^{2} \theta^2_j} = \frac{-1 + 0.2704}{1 + 0.2704} = -0.5743
\end{align}
$$

$$
\begin{align}
\rho_1 &= \frac{-\theta_1 + \sum_{j=1}^{2-1} \theta_j \theta_{j+1}}{1 + \sum_{j=1}^{2} \theta^2_j} = \frac{-0.2 + 0.096}{1 + 0.2704} = -0.0819
\end{align}
$$

$$
\begin{align}
\rho_2 &= \frac{-\theta_2 + \sum_{j=1}^{2-2} \theta_j \theta_{j+1}}{1 + \sum_{j=1}^{2} \theta^2_j} = \frac{0.48 + 0}{1 + 0.2704} = 0.3778  
\end{align}
$$

$$
\begin{align}
\rho_3 &= 0
\end{align}
$$


$$
\begin{align}
\rho_k = {\phi_1}^{|k|}
\end{align}
$$



```{r}
# Exercise 3.1.3

for (i in seq(0,10)){
  cat('autocorrelation at lag ' , i, ': ', (-0.7)^i, '\n')
}

```
